services:
  - type: web
    name: stockai
    runtime: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn stockai.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.14"
